import { Document } from "./core/models.ts";

const document: Document = {
  femaleNames: [
    "Abigail",
    "Ana",
    "Atalía",
    "Azura",
    "Dalila",
    "Débora",
    "Dina",
    "Elena",
    "Elisabet",
    "Ester",
    "Eugenia",
    "Eulalia",
    "Genoveva",
    "Guadalupe",
    "Hanna",
    "Hulda",
    "Ilana",
    "Inés",
    "Inmaculada",
    "Irene",
    "Juana",
    "María",
    "Miriam",
    "Raquel",
    "Sila",
    "Tabita",
    "Adriana",
    "Agatha",
    "Blanca",
    "Bruna",
    "Carlota",
    "Cayetana",
    "Estela",
    "Fiona",
    "Ivet",
    "Ivonne",
    "Jordina",
    "Julieta",
    "Mónica",
    "Nuria",
    "Olivia",
    "Romina",
    "Nona",
    "Andrea",
    "Alicia",
    "Aurora",
    "Aylin",
    "Bárbara",
    "Beatriz",
    "Begoña",
    "Belén",
    "Berta",
    "Bella",
    "Brenda",
    "Candela",
    "Carla",
    "Carmen",
    "Carolina",
    "Catalina",
    "Celeste",
    "Chantal",
    "Clara",
    "Claudia",
    "Cristina",
    "Dánae",
    "Daniela",
    "Desirée",
    "Edurne",
    "Elisabet",
    "Ester",
    "Fabiola",
    "Florencia",
    "Gema",
    "Georgina",
    "Gurutze",
    "Haidée",
    "Inés",
    "Irati",
    "Itziar",
    "Isabel",
    "Jessica",
    "Katia",
    "Lucía",
    "Macarena",
    "Paula",
    "Rita",
    "Sara",
    "Silvia",
    "Sheila",
    "Teresa",
    "Úrsula",
    "Valeria",
    "Adelaida",
    "Agostiña",
    "Águeda",
    "Aine",
    "Aldara",
    "Alexandra",
    "Aloia",
    "Amalia",
    "Antía",
    "Antoñina",
    "Araceli",
    "Beltaine",
    "Catuxa",
    "Erea",
    "Iria",
    "Sabel",
    "Amaia",
    "Ane",
    "Arantxa",
    "Edurne",
    "Estíbaliz",
    "Leire",
    "Maialen",
    "Nagore",
    "Nerea",
    "Olaia",
    "Alma",
    "Amada",
    "Antonella",
    "Appel",
    "Atlas",
    "Bear",
    "Capri",
    "Delfina",
    "Edie",
    "Esmeralda",
    "Estelle",
    "Everly",
    "Francesca",
    "Frankie",
    "Giulia",
    "Leonor",
    "Nahla",
    "Roma",
    "Sabrina",
    "Selena",
    "Vivienne",
    "Willow",
    "Zahara",
    "Adina",
    "Aina",
    "Anel",
    "Aria",
    "Arlene",
    "Ayana",
    "Carey",
    "Carola",
    "Daila",
    "Dora",
    "Eyén",
    "Fiona",
    "Freda",
    "Gilda",
    "Guiomar",
    "Havana",
    "Ikia",
    "Ilse",
    "June",
    "Kaie",
    "Kala",
    "Kora",
    "Lais",
    "Lavinia",
    "Layla",
    "Maira",
    "Miranda",
    "Mirta",
    "Moira",
    "Nara",
    "Nélida",
    "Ofra",
    "Opal",
    "Palma",
    "Taliaa",
    "Telma",
    "Udiya",
    "Winnona",
    "Ada",
    "Ava",
    "Cloe",
    "Ela",
    "Ena",
    "Eva",
    "Flor",
    "Kim",
    "Lea",
    "Lía",
    "Liv",
    "Lúa",
    "Mar",
    "Mia",
    "Noa",
    "Pía",
    "Rut",
    "Sol",
    "Uma",
    "Zoé",
    "Aisha",
    "Dúnya",
    "Fara",
    "Fátima",
    "Jalila",
    "Melissa",
    "Naima",
    "Suhaila",
    "Yamile",
    "Yashira",
    "Yasmin",
    "Zaida",
    "Alessandra",
    "Allegra",
    "Bianca",
    "Carina",
    "Fiorella",
    "Gabriella",
    "Gaia",
    "Nicoletta",
    "Orazia",
    "Stella",
    "Àngels",
    "Anna",
    "Agnés",
    "Carme",
    "Dàlia",
    "Joana",
    "Laia",
    "Llúcia",
    "Mercè",
    "Meritxell:",
    "Montserrat",
    "Neus",
    "Roser",
  ],
  maleNames: [
    "Aaron",
    "Aiden",
    "Alexander",
    "Andrew",
    "Anthony",
    "Arthur",
    "Connor",
    "Charly",
    "Christopher",
    "Elliot",
    "Ethan",
    "Harrison",
    "Jacob",
    "Jeffrey",
    "Jake",
    "Jeremy",
    "Jordan",
    "Joseph",
    "Joshua",
    "Mason",
    "Matthew",
    "Max",
    "Michael",
    "Noah",
    "Riley",
    "Steven",
    "Thomas",
    "Toby",
    "William",
    "Aritz",
    "Axel",
    "Borja",
    "Bruno",
    "Dante",
    "Darío",
    "Derek",
    "Dylan",
    "Elian",
    "Enzo",
    "Gael",
    "Gorka",
    "Ian",
    "Igor",
    "Iker",
    "Isaac",
    "Julen",
    "Kai",
    "Leo",
    "Liam",
    "Luca",
    "Marc",
    "Marcos",
    "Martín",
    "Matías",
    "Noah",
    "Oliver",
    "Unai",
    "Uriel",
    "Nic",
    "Abdiel",
    "Acab",
    "Adán",
    "Ahzià",
    "Caín",
    "Caleb",
    "David",
    "Elías",
    "Eliel",
    "Ezequiel",
    "Gabriel",
    "Goliat",
    "Isaías",
    "Israel",
    "Jared",
    "Jehoram",
    "Jehú",
    "Jesús",
    "Joanix",
    "Jonatan",
    "Jonás",
    "Joaquín",
    "Moisés",
    "Nathan",
    "Noé",
    "Pablo",
    "Salomón",
    "Samuel",
    "Saúl",
    "Uzías",
    "Paolo",
    "Romeo",
    "Cayetano",
    "Benito",
    "Uziel",
    "Quim",
    "Marcos",
    "Yuri",
    "Max",
    "Beltrán",
    "Ignasi",
    "Biel",
    "Martí",
    "Marc",
    "Gil",
    "Abraham",
    "Alberto",
    "Adrián",
    "Agustín",
    "Alan",
    "Aitor",
    "Alejandro",
    "Alexis",
    "Alfonso",
    "Alonso",
    "Andrés",
    "Ángel",
    "Antonio",
    "Álvaro",
    "Carlos",
    "Cristian",
    "Izan",
    "Jorge",
    "Juan",
    "Lorenzo",
    "Lucas",
    "Luis",
    "Darío",
    "Daniel",
    "Diego",
    "Eduardo",
    "Eder",
    "Eloy",
    "Emilio",
    "Eneko",
    "Enrique",
    "Eric",
    "Ernesto",
    "Eugenio",
    "Eusebio",
    "Ezequiel",
    "Fabián",
    "Félix",
    "Felipe",
    "Fernando",
    "Froilán",
    "Gerardo",
    "Gonzalo",
    "Guillermo",
    "Gustavo",
    "Román",
    "Rodrigo",
    "Antón",
    "Anxelo",
    "Brais",
    "Breixo",
    "Caetano",
    "Estevo",
    "Hixinio",
    "Ivo",
    "Lois",
    "Odón",
    "Roi",
    "Roxelio",
    "Xabier",
    "Xacinto",
    "Xaime",
    "Xandro",
    "Xilgorio",
    "Xoan",
    "Uxio",
    "Yago",
  ],
  lastNames: [
    "González",
    "Rodríguez",
    "Gómez",
    "Fernández",
    "López",
    "Díaz",
    "Martínez",
    "Pérez",
    "García",
    "Sánchez",
    "Romero",
    "Sosa",
    "Torres",
    "Álvarez",
    "Ruiz",
    "Ramírez",
    "Flores",
    "Benítez",
    "Acosta",
    "Medina",
    "Herrera",
    "Suárez",
    "Aguirre",
    "Giménez",
    "Gutiérrez",
    "Pereyra",
    "Rojas",
    "Molina",
    "Castro",
    "Ortiz",
    "Silva",
    "Núñez",
    "Luna",
    "Juárez",
    "Cabrera",
    "Ríos",
    "Morales",
    "Godoy",
    "Moreno",
    "Ferreyra",
    "Domínguez",
    "Carrizo",
    "Peralta",
    "Castillo",
    "Ledesma",
    "Quiroga",
    "Vega",
    "Vera",
    "Muñoz",
    "Ojeda",
    "Ponce",
    "Villalba",
    "Cardozo",
    "Navarro",
    "Coronel",
    "Vázquez",
    "Ramos",
    "Vargas",
    "Cáceres",
    "Arias",
    "Figueroa",
    "Córdoba",
    "Correa",
    "Maldonado",
    "Paz",
    "Rivero",
    "Miranda",
    "Mansilla",
    "Farias",
    "Roldán",
    "Méndez",
    "Guzmán",
    "Agüero",
    "Hernández",
    "Lucero",
    "Cruz",
    "Páez",
    "Escobar",
    "Mendoza",
    "Barrios",
    "Bustos",
    "Ávila",
    "Ayala",
    "Blanco",
    "Soria",
    "Maidana",
    "Acuña",
    "Leiva",
    "Duarte",
    "Moyano",
    "Campos",
    "Soto",
    "Martín",
    "Valdez",
    "Bravo",
    "Chávez",
    "Velázquez",
    "Olivera",
    "Toledo",
    "Franco",
    "ortega",
    "Porras",
    "Robalino",
    "Bonilla",
    "Lopez",
  ],
  domains: ["gmail.com", "outlook.com", "yahoo.com", "hotmail.com"],
  bloodtype: ["A -", "A +", "AB -", "AB +", "B -", "B +", "O -", "O +"],
  civilStatus: ["Solter@", "Casad@", "Divorciad@", "Viud@"],
  professions: [
    "Contador",
    "Actor / Actriz",
    "Azafata (avión)",
    "Arqueólogo",
    "Arquitecto",
    "Astronauta",
    "Panadero",
    "Biólog@",
    "Albañil",
    "Conductor/a de autobús",
    "Empresari@, hombre/mujer de negocios",
    "Carnicer@",
    "Portero",
    "Carpinter@",
    "Cajer@",
    "Limpiador",
    "Payaso",
    "Zapatero",
    "Cocinero",
    "Químico",
    "Bailarín",
    "Decorador",
    "Dentista",
    "Diseñador",
    "Médic@",
    "Modista",
    "Basurero (UK)",
    "Economista",
    "Electricista",
    "Ingenier@",
    "Granjero, agricultor",
    "Bombero",
    "Pescador",
    "Florista",
    "Frutero",
    "Jardiner@",
    "geólogo",
    "Peluquer@",
    "Ama de casa",
    "Joyer@",
    "Periodista",
    "Juez",
    "Abogad@",
    "Bibliotecari@",
    "Socorrista",
    "Cartero",
    "Mecánic@",
    "Meteorólogo",
    "Miner@",
    "Modelo",
    "Niñera",
    "Monja",
    "Enfermer@",
    "Niñera",
    "Pintor",
    "Pastelero, repostero",
    "Farmaceútico",
    "Fotógrafo",
    "Físico",
    "Fontanero",
    "Policía",
    "Político",
    "Conserje",
    "Cartero",
    "Cura",
    "Profesor/a (Universidad)",
    "Programador",
    "Psiquiatra",
    "Psicólog@",
    "Recepcionista",
    "Investigador",
    "Mariner@",
    "Vendedor",
    "Científico",
    "Secretario",
    "Zapatero",
    "Dependiente/a de una tienda",
    "Cantante",
    "Trabajador social",
    "deportista",
    "Cirujano",
    "Taxista",
    "Profesor/a (Primaria y Secundaria)",
    "Telefonista",
    "Agente de viajes",
    "Camioner@",
    "Veterinario",
    "Camarer@",
    "Escritor",
  ],
  universities: [
    "Universidad San Francisco de Quito",
    "Escuela Politécnica Nacional",
    "Escuela Superior Politécnica del Litoral",
    "Universidad Técnica Particular de Loja",
    "Pontificia Universidad Católica del Ecuador",
    "Universidad de las Fuerzas Armadas ESPE (Escuela Politécnica del Ejército)",
    "Universidad Politécnica Salesiana Ecuador",
    "Universidad de Cuenca",
    "Universidad Central del Ecuador",
    "Universidad de las Américas Ecuador",
    "Universidad Técnica de Ambato",
    "Universidad Técnica del Norte",
    "Instituto de Altos Estudios Nacionales",
    "FLACSO Ecuador Facultad Latinoamericana de Ciencias Sociales",
    "Universidad de Guayaquil",
    "Escuela Superior Politécnica de Chimborazo",
    "Universidad de Especialidades Espíritu Santo",
    "Universidad Nacional de Loja",
    "Universidad UTE",
    "Universidad del Azuay",
    "Universidad Internacional del Ecuador",
    "Universidad Andina Simón Bolívar Ecuador",
    "Universidad Técnica de Machala",
    "Universidad Nacional de Chimborazo",
    "Yachay Tech",
    "Universidad Católica de Santiago de Guayaquil",
    "Universidad del Pacífico Escuela de Negocios",
    "Universidad Estatal Amazónica",
    "Universidad Estatal Península de Santa Elena",
    "Universidad Tecnológica Indoamérica",
    "Universidad Católica de Cuenca",
    "Universidad Laica Eloy Alfaro de Manabi",
    "Universidad Técnica de Cotopaxi",
    "Universidad Estatal de Milagro",
    "Universidad Laica Vicente Rocafuerte de Guayaquil",
    "Universidad Técnica Estatal de Quevedo",
    "Universidad Particular Internacional SEK",
    "Universidad Metropolitana del Ecuador",
    "Universidad Nacional de Educación UNAE",
    "Universidad Particular San Gregorio de Portoviejo USGP",
    "Universidad Casa Grande",
    "Universidad Estatal de Bolívar",
    "Universidad Estatal del Sur de Manabí UNESUM",
    "Universidad Técnica de Manabí",
    "Universidad de Otavalo",
    "Escuela Superior Politécnica Agropecuaria de Manabí",
    "Universidad Regional Autónoma de los Andes UNIANDES",
    "Universidad Técnica de Babahoyo",
    "Universidad Politécnica Estatal del Carchi UPEC",
    "Universidad Agraria del Ecuador",
    "Universidad Tecnológica ECOTEC",
    "Pontificia Universidad Católica Sede Ibarra",
    "Universidad de los Hemisferios",
    "Universidad Tecnológica Israel",
    "Pontificia Universidad Católica del Ecuador Sede Ambato",
    "Universidad Técnica Luis Vargas Torres de Esmeraldas",
    "Universidad Tecnológica Empresarial de Guayaquil",
    "Universidad Santa María de Chile Campus Guayaquil",
    "Escuela de Direccion de Empresas",
    "Pontificia Universidad Católica de Ecuador Sede Santo Domingo",
    "Universidad Iberoamericana del Ecuador",
    "Universidad de Especialidades Turisticas",
    "Universidad Internacional de La Rioja Ecuador",
  ],
};

export default document;
